export const IS_FRESH_YEAST = "IS_FRESH_YEAST"

export const INPUT_HANDLER = "INPUT_HANDLER"
export const RESET_INPUTS = "RESET_INPUTS"
export const CALCULATE_INPUTS = "CALCULATE_INPUTS"
export const BACK_TO_CALCULATION_INPUTS = "BACK_TO_CALCULATION_INPUTS"

export const SWITCH_TO_EN = "SWITCH_TO_EN"
export const SWITCH_TO_RU = "SWITCH_TO_RU"